version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-api
    restart: always
    ports:
      - "6060"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hotel-network

networks:
  hotel-network:
    name: hotel-network
